---
- name: install dependencies (apt)
  become: yes
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present

- name: install key (apt)
  become: yes
  apt_key:
    url: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'
    state: present

- name: register empty variable trusted for gpgcheck
  set_fact:
    trusted: ''
  when: visual_studio_code_gpgcheck

- name: register variable trusted=yes for gpgcheck
  set_fact:
    trusted: 'trusted=yes'
  when: not visual_studio_code_gpgcheck

- name: install VS Code repo (apt)
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64 {{ trusted }}] {{ visual_studio_code_mirror }}/repos/code stable main'
    filename: vscode
    state: present
  when: not visual_studio_code_skip_add_repo

- name: install VS Code (apt)
  become: yes
  apt:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
    state: present
